.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. pexa_qt test_pexa_qt
clean: FORCE
	$(MAKE) -C .. pexa_qt_clean test_pexa_qt_clean
check: FORCE
	$(MAKE) -C .. test_pexa_qt_check
pexa-qt pexa-qt.exe: FORCE
	 $(MAKE) -C .. pexa_qt
